### PR TITLE
Mp/keys api client user principals updates

### PR DESCRIPTION
**Pull request by marcparadise**
This adds tests for external-facing changes to oc_erchef in PRs [1-6]/8: 

* Key generation via keys endpoint 
* new v1 behaviors spec that calls out and tests behaviors new to v1 that don't  
  fit easily into the existing test framework. Adds org creation, client, and user tests. 
* principals API v1 behavior, which will run by default. 
 
To support this, I made the following additional changes:

* modify server_api_version to be a global so that it can be easily set, though I added an accessor for it to at least hide the fact...  I'm not happy about this answer, but given the way pedant does its initialization and the fact that we do a nested test run for org validation, I ran out of ideas. Suggestions encouraged. 
* focii targets for --focus-api-v0 and --focus-api-v1, as wel as a couple of other missing targets that we had already existing in the code. 
* Added matcher support for arrays containing nested hashes, and more consistent handling of field types at any level though still imperfect.    Also expanded matcher test coverage.

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## Non-GitHub Verified Committers

There are 1 commit author(s) whose commits are authored by a non-GitHub verified email address. Chef will have to manually verify that they are authorized to contribute.

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by tylercloke** [comment]
Good enough. Let's just get this stuff merged so we can move on.

**Comment by marcparadise** [comment]
Hm, I thought this was already merged. Looking to see if I had it on another branch.

**Comment by marcparadise** [comment]
Indeed it was, I merged and pushed locally and it looks like github didn't pick up on it. Closing the PR.

**Pull request closed without merging**
